import ClassInviteTable from "../../components/ClassInviteTable";
import Head from "next/head";
import Navbar from "../../components/navbar";
import Link from "next/link";
import Modal from "../../components/modal";

export async function getServerSideProps(ctx) {
  const output = [
    {
      classroomName: "301",
      classroomId: "c301",
      description: "In main building 3rd floor",
    },
    {
      classroomName: "302",
      classroomId: "c302",
      description: "In main building 3rd floor",
    },
  ];

  return {
    props: { classrooms: output },
  };
}

export default function Classes({ classrooms }) {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <>
        <Navbar>
          <div className="border-solid border-2 pl-4 pr-4">
            <Link href={"/classes"}>Classes</Link>
          </div>
          <div className="border-solid border-2 pl-4 pr-4">
            <Link href={"/"}> Menu</Link>
          </div>
        </Navbar>

        <div className={"text-center p-10"}>
          <h1> Copy invite code by clicking on your preferred class. </h1>
        </div>

        {<Modal />}
        {classrooms.map((classrooms) => (
          <div key={classrooms.id}>
            <a>
              <ClassInviteTable classes={classrooms}></ClassInviteTable>
            </a>
          </div>
        ))}
      </>
    </>
  );
}
